{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "build-api.fullname" . }}
  labels:
    {{- include "build-api.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - builder-hub.dev
  resources:
  - buildkitbuilders
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - builder-template.builder-hub.dev
  resources:
  - buildkitbuildertemplates
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "build-api.fullname" . }}
  labels:
    {{- include "build-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "build-api.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "build-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
