# Values for: helm upgrade --install build-operator charts/build-operator
installCRDs: true
operator:
  image:
    repository: ghcr.io/builderhub/build-operator
    tag: latest
    pullPolicy: IfNotPresent
