{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "build-operator.fullname" . }}-manager
  labels:
    {{- include "build-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [configmaps, persistentvolumeclaims, pods, services]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [apps]
    resources: [statefulsets]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [traefik.io]
    resources: [ingressroutes, ingressroutetcps]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [builder-hub.dev]
    resources: [buildkitbuilders]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [builder-hub.dev]
    resources: [buildkitbuilders/finalizers]
    verbs: [update]
  - apiGroups: [builder-hub.dev]
    resources: [buildkitbuilders/status]
    verbs: [get, patch, update]
  - apiGroups: [builder-template.builder-hub.dev]
    resources: [buildkitbuildertemplates]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "build-operator.fullname" . }}-manager
  labels:
    {{- include "build-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "build-operator.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "build-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "build-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "build-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "build-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "build-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "build-operator.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "build-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
